import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='kr'>
      <body className={inter.className}>
        <Header />
        <main>
          <div className='max-w-screen-xl mx-auto p-10 flex flex-row w-full'>
            <Sidebar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
